# Generated by Django 5.2.7 on 2025-11-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.CharField(db_column='id', max_length=2, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='libelle', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Etat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FraisForfait',
            fields=[
                ('id', models.CharField(db_column='id', max_length=3, primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, db_column='libelle', max_length=20, null=True)),
                ('montant', models.DecimalField(blank=True, db_column='montant', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'FraisForfait',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.CharField(db_column='id', max_length=4, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='nom', max_length=30, null=True)),
                ('prenom', models.CharField(blank=True, db_column='prenom', max_length=30, null=True)),
                ('login', models.CharField(blank=True, db_column='login', max_length=20, null=True)),
                ('mdp', models.CharField(blank=True, db_column='mdp', max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, db_column='adresse', max_length=40, null=True)),
                ('cp', models.CharField(blank=True, db_column='cp', max_length=5, null=True)),
                ('ville', models.CharField(blank=True, db_column='ville', max_length=30, null=True)),
                ('dateembauche', models.DateField(blank=True, db_column='dateEmbauche', null=True)),
            ],
            options={
                'db_table': 'Visiteur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneFraisHorsForfait',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('mois', models.CharField(db_column='mois', max_length=6)),
                ('libelle', models.CharField(blank=True, db_column='libelle', max_length=100, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('montant', models.DecimalField(blank=True, db_column='montant', decimal_places=2, max_digits=10, null=True)),
                ('idvisiteur', models.ForeignKey(db_column='idVisiteur', on_delete=django.db.models.deletion.CASCADE, to='frais.visiteur')),
            ],
            options={
                'db_table': 'LigneFraisHorsForfait',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneFraisForfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(db_column='mois', max_length=6)),
                ('quantite', models.IntegerField(blank=True, db_column='quantite', default=0, null=True)),
                ('idfraisforfait', models.ForeignKey(db_column='idFraisForfait', on_delete=django.db.models.deletion.CASCADE, to='frais.fraisforfait')),
                ('idvisiteur', models.ForeignKey(db_column='idVisiteur', on_delete=django.db.models.deletion.CASCADE, to='frais.visiteur')),
            ],
            options={
                'db_table': 'LigneFraisForfait',
                'managed': True,
                'unique_together': {('idvisiteur', 'mois', 'idfraisforfait')},
            },
        ),
        migrations.CreateModel(
            name='FicheFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(db_column='mois', max_length=6)),
                ('nbjustificatifs', models.IntegerField(blank=True, db_column='nbJustificatifs', default=0, null=True)),
                ('montantvalide', models.DecimalField(blank=True, db_column='montantValide', decimal_places=2, default=0, max_digits=10, null=True)),
                ('datemodif', models.DateField(blank=True, db_column='dateModif', null=True)),
                ('idetat', models.ForeignKey(db_column='idEtat', default='CR', on_delete=django.db.models.deletion.CASCADE, to='frais.etat')),
                ('idvisiteur', models.ForeignKey(db_column='idVisiteur', on_delete=django.db.models.deletion.CASCADE, to='frais.visiteur')),
            ],
            options={
                'db_table': 'FicheFrais',
                'managed': True,
                'unique_together': {('idvisiteur', 'mois')},
            },
        ),
    ]
