# Generated by Django 5.2.7 on 2025-11-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteur',
            name='mdp',
            field=models.CharField(blank=True, db_column='mdp', max_length=255, null=True),
        ),
    ]
